### ISSUE TITLE
Bad plot k18 created

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/chiapos#131]
I managed to create a bad plot that segfaults sometimes when getting qualities
It's a k18 though, so this issue might not be present in the big ones
anyway, it might be worth exploring. The plot id is: "22d67d64197d6787da61cd31302832ab8667097239e38cf442eb8a5b19cbc074"

Made using stripe size of 2000, b=100.

With a "chia plots check" of 200,000, found a crash:
munmap_chunk(): invalid pointer

**Comment by hoffmang9** [comment]
We're ignoring k's below 22 so closing.
