### ISSUE TITLE
Plotter stuck on retry loop after intermittent loss of connection to HDD

### ISSUE THREAD

**Issue by martomi** [Chia-Network/chiapos#152]
How to reproduce:
1. Unplug HDD during compression step
2. Plotter detects incomplete write and enters retry loop (every 5 minutes)
3. Reconnect HDD -> plotter won't be able to successfully resume

Seems to me that the file needs to be [reopened](https://github.com/Chia-Network/chiapos/blob/e3e1acb9508497a4d4a9f4c6642ab7bd907a1aaa/src/disk.hpp#L173) inside the loop. Or perhaps this use-case was not intended to be a feature?

**Comment by hoffmang9** [comment]
Resuming plotting hasn't been implemented yet but will be.
