### ISSUE TITLE
[BUG] Plots freeze in phase 2 backpropagation, need to be killed

### ISSUE THREAD

**Issue by gumba4** [Chia-Network/chiapos#164]
**Describe the bug**
Some of my plots (say 25%) freeze in phase 2, i.e. no further progress is reported after the freeze, for hours (then I kill the process manually).
The log files do not continue. No new files in the temp dir are created.
Otherwise, the process seems to continue: CPU time is being used similar to alive plots, ram stays normal. File locks on log file still exist.

Normally a plot finishes in 9 hours, I usually kill the stuck ones after 12 or so.

Plots were started with

> chia plots create -k 32 -r 4 -u 128 -b 4520 -t /mnt/chiatmp -d /mnt/chiaplots -e

**To Reproduce**
Don't know. For me it's just a chance of say 25%.

**Expected behavior**
Plot should not freeze

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**

- OS: Linux
- OS Ubuntu 20.04 LTS latest updates
- CPU:  Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

**Additional context**
- Chia beta 27, freshly installed as instructed (no update)
- Temp dir is formatted as ext4. It's a Corsair MP600 NVME SSD.
- Always more than 25gb ram free, swap disabled
- Temp dir always has more than 300gb free

Please ask for further info. I will attach log files of three such occurences.

**Comment by gumba4** [comment]
Another plot process just froze in the same way, again in phase 2. The process still uses cpu (i think one thread 100%) with ram staying at 5.1G. It has no IO activity though (monitored with iotop). Meanwhile other processes continue running as expected.
Any idea on what I could try?
I attach the log.
[2021-02-19-10:59:08.log](https://github.com/Chia-Network/chiapos/files/6011283/2021-02-19-10.59.08.log)

**Comment by mariano54** [comment]
It could be bad ram. Try using different ram or running a ram test

**Comment by gumba4** [comment]
Thanks for your help. I did a ram test (memtest86), which showed no errors.
I also changed the tmp drive partition to XFS, which has no apparent effect. Problem is still occurring.
The fails only happen in phase 2, another one right now. Other plot processes continue unaffected.
Maybe it is a problem with the storage my tmp dir is on.
Do you have any advice regarding logfiles or what to investigate further?

**Comment by gumba4** [comment]
Logfile of latest incident fwiw:
[2021-02-21-14:02:36.log](https://github.com/Chia-Network/chiapos/files/6018071/2021-02-21-14.02.36.log)

**Comment by gumba4** [comment]
Another one:
[2021-02-21-16:18:36.log](https://github.com/Chia-Network/chiapos/files/6018301/2021-02-21-16.18.36.log)
Here a log file of the currently open files by the process (made with lsof):
[lsof_of_a_stuck_plot_process.txt](https://github.com/Chia-Network/chiapos/files/6018302/lsof_of_a_stuck_plot_process.txt)
The process has no IO activity at all, for at least 30 minutes. Based on pidstat, there seems to be no ram activity either.
I hope I get another temp drive soon, so that I can check that one.

**Comment by gumba4** [comment]
After replacing my tmp device didn't help, I ran the ram check once more and this time some errors were reported in the random pattern test. I replaced the ram and will report again when I know if the plots are now running smoothly.

**Comment by gumba4** [comment]
No more problems after replacing ram, so closing this.
Sorry for the disturbance.
