### ISSUE TITLE
[BUG] Beta 19: Not enough memory for sort in memory

### ISSUE THREAD

**Issue by matteomonti** [Chia-Network/chiapos#167]
**Describe the bug**
Plotting fails in phase 2, when compressing tables 2 and 3. The plot reports "Not enough memory for sort in memory".
Configuration: k = 32; swap space available = 512 GB; target space available = 8 TB; memory allocated = 8 GB.

**To Reproduce**

1. Go to 'Plots'.
2. Click on 'New plot'.
3. Select 'k = 32'.
3. In 'Advanced Configuration', allocate 8 GB of memory; leave the number of buckets to 0.
4. Click on 'Open log'.
5. Error shows up when compressing tables 2 and 3

**Expected behavior**

**Desktop (please complete the following information):**

- OS: Windows 10
- CPU: AMD Ryzen 7 5800X

**Additional context**
This behaviour seems identical to what reported on [Reddit](https://www.reddit.com/r/chia/comments/kl6392/error_not_enough_memory_for_sort_in_memory/) for Beta 18. The post suggested downgrading to Beta 17 until Beta 19 was available. I assumed Beta 19 fixed that bug, so I upgraded straight from 17 to 19, but the bug still seems to be there. I am now plotting by forcing 64 buckets. I will report if that works!

**Comment by hoffmang9** [comment]
Buckets are now correctly set in the GUI.
