### ISSUE TITLE
BUG: Build fails - gmake: *** [Makefile:114: all] Error 2 - Fedora based OS.

### ISSUE THREAD

**Issue by Chewbakka-Wakka** [Chia-Network/chiapos#196]
Most of the build seems to run and near the end I see the following:

[ 88%] Building ASM object CMakeFiles/ProofOfSpace.dir/src/b3/blake3_sse41_x86-64_unix.S.o
[ 91%] Building ASM object CMakeFiles/chiapos.dir/src/b3/blake3_sse41_x86-64_unix.S.o
gmake[2]: *** [CMakeFiles/ProofOfSpace.dir/build.make:82: CMakeFiles/ProofOfSpace.dir/src/cli.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:150: CMakeFiles/ProofOfSpace.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake[2]: *** [CMakeFiles/RunTests.dir/build.make:82: CMakeFiles/RunTests.dir/tests/test-main.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:123: CMakeFiles/RunTests.dir/all] Error 2
[ 94%] Linking CXX shared module ../lib.linux-x86_64-3.8/chiapos.cpython-38-x86_64-linux-gnu.so
[ 94%] Built target chiapos
gmake: *** [Makefile:114: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 203, in <module>
    setup(
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 38, in run
    self.build_extension(ext)
  File "setup.py", line 70, in build_extension
    subprocess.check_call(
  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j', '6']' returned non-zero exit status 2.
error: Bad exit status from /var/tmp/rpm-tmp.rhA1XY (%build)

Any thoughts or anything you need me to provide? I am quite sure I meet all the dependencies.

**Comment by Chewbakka-Wakka** [comment]
I tried this again on the 1.0.0 release and same occurs

**Comment by Chewbakka-Wakka** [comment]
same on 1.0.1,  using cmake-3.19.7-2.fc35.x86_64

**Comment by arvidn** [comment]
do you see any output before the part you posted that looks like errors? I would expect `gmake` would also print the actual output from the compiler.

**Comment by Chewbakka-Wakka** [comment]
The only other errors that appear prior are as follows:

[ 27%] Linking CXX static library libuint128.a
[ 27%] Built target uint128
Scanning dependencies of target RunTests
[ 30%] Building CXX object CMakeFiles/RunTests.dir/tests/test-main.cpp.o
In file included from /usr/include/signal.h:315,
                 from /home/ss/rpmbuild/BUILD/chiapos-1.0.1/tests/../lib/include/catch.hpp:8034,
                 from /home/ss/rpmbuild/BUILD/chiapos-1.0.1/tests/test-main.cpp:16:
/home/ss/rpmbuild/BUILD/chiapos-1.0.1/tests/../lib/include/catch.hpp:10822:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
10822 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/bits/sigstksz.h:24,
                 from /usr/include/signal.h:315,
                 from /home/ss/rpmbuild/BUILD/chiapos-1.0.1/tests/../lib/include/catch.hpp:8034,
                 from /home/ss/rpmbuild/BUILD/chiapos-1.0.1/tests/test-main.cpp:16:
/usr/include/unistd.h:630:17: note: ‘long int sysconf(int)’ declared here
  630 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
In file included from /home/ss/rpmbuild/BUILD/chiapos-1.0.1/tests/test-main.cpp:16:
/home/ss/rpmbuild/BUILD/chiapos-1.0.1/tests/../lib/include/catch.hpp:10881:45: error: size of array ‘altStackMem’ is not an integral constant-expression
10881 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~

**Comment by Chewbakka-Wakka** [comment]
Not seen in 1.0.2
