### ISSUE TITLE
[BUG] Plot process gets killed on backpropagation

### ISSUE THREAD

**Issue by yEinFallsLos** [Chia-Network/chiapos#209]
### Describe the bug
When the plotter reaches table 6 for backpropagation the process randomly exits. The last message just says 'Killed', which is not found in the log and only visible if run trough CLI.
Setting the buffer size to anything lower/higher didn't make any difference.
Plotting with k=25 works just fine.
Also, I've run the process 3 times now (with different ram settings) and it ALWAYS crashed at backpropagation on table 6.

### Sample Output
```sh
...
Starting phase 2/4: Backpropagation into tmp files... Mon Apr 19 15:17:10 2021
Backpropagating on table 7
scanned table 7
scanned time =  194.997 seconds. CPU (45.350%) Mon Apr 19 15:20:25 2021
sorting table 7
Backpropagating on table 6
Killed
(venv) chia@chia:~/chia-blockchain$
```
Log File: [plotter_log_43b3a6a3-c5cd-47a8-aa94-dbbe82342a85.txt](https://github.com/Chia-Network/chiapos/files/6336848/plotter_log_43b3a6a3-c5cd-47a8-aa94-dbbe82342a85.txt)

### Environment
OS: Debian 10.9 64bit (4.19.0-16-amd64)
CPU: Intel Xeon E5-2420 v2
RAM: 32gb ECC
Temp/Final Disk: 16TB Exos X16 (one drive for both)
File System: ext4

**Comment by hoffmang9** [comment]
Have you successfully completed one k32 at a time?

**Comment by yEinFallsLos** [comment]
I always did only one at a time, so no.

**Comment by hoffmang9** [comment]
This is usually a RAM problem but ECC RAM should be less susceptible

**Comment by yEinFallsLos** [comment]
Also, it is always at exactly the same spot, so random bit flips wouldn't make much sense

**Comment by yEinFallsLos** [comment]
Solved: There was some weird behavior of the kernel, it killed the process because it thought it was out of memory although the memory was nearly empty.
Fixed it now, sorry for bothering you
