### ISSUE TITLE
[Enhancement] 40% Faster Disk Plotting - disk.hpp - Chia Plotting Bottleneck

### ISSUE THREAD

**Issue by InfuehrDaniel** [Chia-Network/chiapos#213]
Analyzing your Plotting Application in steps 2/3: It is bound by memory copy and seek speed - the abstraction you chose for a harddisk in disk.hpp is a streaming device. 

**Much better**  - use memory mapped IO directly. No buffer needed at all. The operating system maps its IO pages directly into your application. A 100GB **file becomes a pointer** where you can read and write **in memory** - but in reality you are writing to disk in a very smart way (details are handled by the OS). This is much faster than  random seeking - even with the buffers you are using. 

**Win32**: [CreatefileMappingW](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-createfilemappingw)
**Linux**: [mmap](https://man7.org/linux/man-pages/man2/mmap.2.html)

A quick and dirty win32 CreatefileMappingW impl for disk.hpp runs 40% faster for step 2 on my machine
1588s -> 981s

This is still with copying all the bytes from pointer to pointer. 
![image](https://user-images.githubusercontent.com/82674952/115922314-095eb100-a47d-11eb-81d6-f153a74bbc98.png)

**With memory mapped IO there is no need to copy anything!**

The fastest way to find in a file (uses the same idea) is here: https://stackoverflow.com/questions/17925051/fast-textfile-reading-in-c
(Only works for non resizable files (sorting is PERFECT))

**Comment by arvidn** [comment]
yes, this is on the roadmap.

**Comment by arvidn** [comment]
I'd be happy to review a patch if you have one. keep in mind that we want to still work on windows, MacOS, Linux, BSD and possibly other platforms that don't provide `mmap`, so we'd likely need multiple implementations of the disk abstraction.

**Comment by arvidn** [comment]
As you may have noticed, `BufferedDisk` has an interface that's been prepared to support zero-copy mmap.

**Comment by QuantumLiu** [comment]
It make sense, have you already PR?

**Comment by QuantumLiu** [comment]
I modified Read and Write function, but got error.
```
    void Read(uint64_t begin, uint8_t *memcache, uint64_t length)
    {
        Open(retryOpenFlag);
#if ENABLE_LOGGING
        disk_log(filename_, op_t::read, begin, length);
#endif
        // Seek, read, and replace into memcache
        if ((!bReading) || (begin != readPos)) {
#ifdef _WIN32
            _fseeki64(f_, begin, SEEK_SET);
#else
            // fseek() takes a long as offset, make sure it's wide enough
            static_assert(sizeof(long) >= sizeof(begin));
            ::fseek(f_, begin, SEEK_SET);
#endif
            bReading = true;
        }

        uint64_t amtread=0;
        int fd_i=fileno(f_);
        struct stat fileInfo = {0};
        if (fstat(fd_i, &fileInfo) == -1)
        {
            perror("Error getting the file size");
            exit(EXIT_FAILURE);
        }
        
        if (fileInfo.st_size == 0)
        {
            fprintf(stderr, "Error: File is empty, nothing to do\n");
            exit(EXIT_FAILURE);
        }


        char *map = (char *)  mmap(NULL, length, PROT_READ, MAP_SHARED, fd_i, 0);
        if (map == MAP_FAILED)
        {
            close(fd_i);
            perror("Error mmapping the file");
            exit(EXIT_FAILURE);
        }

        
        memcpy(memcache, map, length);
        amtread+=length;
        
        // Don't forget to free the mmapped memory
        if (munmap(map, length) == -1)
        {
            close(fd_i);
            perror("Error un-mmapping the file");
            exit(EXIT_FAILURE);
        }

        readPos = begin + amtread;
        if (amtread != length) {
            std::cout << "Only read " << amtread << " of " << length << " bytes at offset "
                        << begin << " from " << filename_ << "with length " << writeMax
                        << ". Error " << ferror(f_) << ". Retrying in five minutes." << std::endl;
            std::this_thread::sleep_for(5min);
        }


    }

    void Write(uint64_t begin, const uint8_t *memcache, uint64_t length)
    {
        Open(writeFlag | retryOpenFlag);
#if ENABLE_LOGGING
        disk_log(filename_, op_t::write, begin, length);
#endif
        // Seek and write from memcache
        uint64_t amtwritten=0;
        // do {
            if ((bReading) || (begin != writePos)) {
#ifdef _WIN32
                _fseeki64(f_, begin, SEEK_SET);
#else
                // fseek() takes a long as offset, make sure it's wide enough
                static_assert(sizeof(long) >= sizeof(begin));
                ::fseek(f_, begin, SEEK_SET);
#endif
                bReading = false;
            }
            uint64_t len=length+1;
            int fd_o=fileno(f_);


 
            if (fd_o == -1)
            {
                perror("Error opening file for writing");
                exit(EXIT_FAILURE);
            }

            if (lseek(fd_o, len-1, SEEK_SET) == -1)
            {
                close(fd_o);
                perror("Error calling lseek() to 'stretch' the file");
                exit(EXIT_FAILURE);
            }

            if (write(fd_o, "", 1) == -1)
            {
                close(fd_o);
                perror("Error writing last byte of the file");
                exit(EXIT_FAILURE);
            }

            char *buffer = (char *) mmap(NULL, len, PROT_WRITE, MAP_SHARED, fd_o, 0);

            if (buffer == MAP_FAILED)
            {
                close(fd_o);
                perror("Error mmapping the file");
                exit(EXIT_FAILURE);
            }
            
            memcpy(buffer, memcache, len);
            amtwritten += len;
            if (msync(buffer, len, MS_SYNC) == -1)
            {
                perror("Could not sync the file to disk");
            }
            
            // Don't forget to free the mmapped memory
            if (munmap(buffer, len) == -1)
            {
                close(fd_o);
                perror("Error un-mmapping the file");
                exit(EXIT_FAILURE);
            }

            writePos = begin + amtwritten;
            if (writePos > writeMax)
                writeMax = writePos;
            if (amtwritten-1!= length) {
                std::cout << "Only wrote " << amtwritten << " of " << length << " bytes at offset "
                          << begin << " to " << filename_ << "with length " << writeMax
                          << ". Error " << ferror(f_) << ". Retrying in five minutes." << std::endl;
                std::this_thread::sleep_for(5min);
            }
        // } while (amtwritten != length);
    }

```

```
$ ./ProofOfSpace -k 25 -f "plot.dat"  create
operation: create
Generating plot for k=25 filename=plot.dat id=022fb42c08c12de3a6af053880199806532e79515f94e83461612101f9412f9e


Starting plotting progress into temporary dirs: . and .
ID: 022fb42c08c12de3a6af053880199806532e79515f94e83461612101f9412f9e
Plot size is: 25
Buffer size is: 4608MiB
Using 16 buckets
Using 2 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Sat May  1 04:06:36 2021
Computing table 1
F1 complete, time: 2.083 seconds. CPU (108.38%) Sat May  1 04:06:38 2021
Computing table 2
	Bucket 0 uniform sort. Ram: 4.441GiB, u_sort min: 0.055GiB, qs min: 0.014GiB.
	Bucket 1 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
	Bucket 2 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
	Bucket 3 uniform sort. Ram: 4.441GiB, u_sort min: 0.055GiB, qs min: 0.014GiB.
	Bucket 4 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
	Bucket 5 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
	Bucket 6 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
	Bucket 7 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
	Bucket 8 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
	Bucket 9 uniform sort. Ram: 4.441GiB, u_sort min: 0.055GiB, qs min: 0.014GiB.
	Bucket 10 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
	Bucket 11 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
	Bucket 12 uniform sort. Ram: 4.441GiB, u_sort min: 0.055GiB, qs min: 0.014GiB.
	Bucket 13 uniform sort. Ram: 4.441GiB, u_sort min: 0.055GiB, qs min: 0.014GiB.
	Bucket 14 uniform sort. Ram: 4.441GiB, u_sort min: 0.055GiB, qs min: 0.014GiB.
	Bucket 15 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
	Total matches: 5194691
Caught exception: Matches do not match with number of write entries 5194691 5195139
terminate called after throwing an instance of 'std::exception'
  what():  std::exception
Aborted (core dumped)
```
Do you have any idea to fix it?

**Comment by QuantumLiu** [comment]
I tried to change FileDisk Write and Read to mapped IO, but got error.
Do you have any idea to fix it?
```
    void Read(uint64_t begin, uint8_t *memcache, uint64_t length)
    {
        Open(retryOpenFlag);
#if ENABLE_LOGGING
        disk_log(filename_, op_t::read, begin, length);
#endif
        // Seek, read, and replace into memcache
        if ((!bReading) || (begin != readPos)) {
#ifdef _WIN32
            _fseeki64(f_, begin, SEEK_SET);
#else
            // fseek() takes a long as offset, make sure it's wide enough
            static_assert(sizeof(long) >= sizeof(begin));
            ::fseek(f_, begin, SEEK_SET);
#endif
            bReading = true;
        }

        uint64_t amtread=0;
        int fd_i=fileno(f_);
        struct stat fileInfo = {0};
        if (fstat(fd_i, &fileInfo) == -1)
        {
            perror("Error getting the file size");
            exit(EXIT_FAILURE);
        }
        
        if (fileInfo.st_size == 0)
        {
            fprintf(stderr, "Error: File is empty, nothing to do\n");
            exit(EXIT_FAILURE);
        }


        char *map = (char *)  mmap(NULL, length, PROT_READ, MAP_SHARED, fd_i, 0);
        if (map == MAP_FAILED)
        {
            close(fd_i);
            perror("Error mmapping the file");
            exit(EXIT_FAILURE);
        }

        
        memcpy(memcache, map, length);
        amtread+=length;
        
        // Don't forget to free the mmapped memory
        if (munmap(map, length) == -1)
        {
            close(fd_i);
            perror("Error un-mmapping the file");
            exit(EXIT_FAILURE);
        }

        readPos = begin + amtread;
        if (amtread != length) {
            std::cout << "Only read " << amtread << " of " << length << " bytes at offset "
                        << begin << " from " << filename_ << "with length " << writeMax
                        << ". Error " << ferror(f_) << ". Retrying in five minutes." << std::endl;
            std::this_thread::sleep_for(5min);
        }


    }

    void Write(uint64_t begin, const uint8_t *memcache, uint64_t length)
    {
        Open(writeFlag | retryOpenFlag);
#if ENABLE_LOGGING
        disk_log(filename_, op_t::write, begin, length);
#endif
        // Seek and write from memcache
        uint64_t amtwritten=0;
        // do {
            if ((bReading) || (begin != writePos)) {
#ifdef _WIN32
                _fseeki64(f_, begin, SEEK_SET);
#else
                // fseek() takes a long as offset, make sure it's wide enough
                static_assert(sizeof(long) >= sizeof(begin));
                ::fseek(f_, begin, SEEK_SET);
#endif
                bReading = false;
            }
            uint64_t len=length+1;
            int fd_o=fileno(f_);


 
            if (fd_o == -1)
            {
                perror("Error opening file for writing");
                exit(EXIT_FAILURE);
            }

            if (lseek(fd_o, len-1, SEEK_SET) == -1)
            {
                close(fd_o);
                perror("Error calling lseek() to 'stretch' the file");
                exit(EXIT_FAILURE);
            }

            if (write(fd_o, "", 1) == -1)
            {
                close(fd_o);
                perror("Error writing last byte of the file");
                exit(EXIT_FAILURE);
            }

            char *buffer = (char *) mmap(NULL, len, PROT_WRITE, MAP_SHARED, fd_o, 0);

            if (buffer == MAP_FAILED)
            {
                close(fd_o);
                perror("Error mmapping the file");
                exit(EXIT_FAILURE);
            }
            
            memcpy(buffer, memcache, len);
            amtwritten += (len-1);
            if (msync(buffer, len, MS_SYNC) == -1)
            {
                perror("Could not sync the file to disk");
            }
            
            // Don't forget to free the mmapped memory
            if (munmap(buffer, len) == -1)
            {
                close(fd_o);
                perror("Error un-mmapping the file");
                exit(EXIT_FAILURE);
            }

            writePos = begin + amtwritten;
            if (writePos > writeMax)
                writeMax = writePos;
            if (amtwritten!= length) {
                std::cout << "Only wrote " << amtwritten << " of " << length << " bytes at offset "
                          << begin << " to " << filename_ << "with length " << writeMax
                          << ". Error " << ferror(f_) << ". Retrying in five minutes." << std::endl;
                std::this_thread::sleep_for(5min);
            }
        // } while (amtwritten != length);
    }

```

The error LOG:
```
chiapos/build$ ./ProofOfSpace -k 25 -f "plot.dat"  create
operation: create
Generating plot for k=25 filename=plot.dat id=022fb42c08c12de3a6af053880199806532e79515f94e83461612101f9412f9e


Starting plotting progress into temporary dirs: . and .
ID: 022fb42c08c12de3a6af053880199806532e79515f94e83461612101f9412f9e
Plot size is: 25
Buffer size is: 4608MiB
Using 16 buckets
Using 2 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Sat May  1 04:49:00 2021
Computing table 1
F1 complete, time: 2.018 seconds. CPU (105.68%) Sat May  1 04:49:02 2021
Computing table 2
	Bucket 0 uniform sort. Ram: 4.441GiB, u_sort min: 0.055GiB, qs min: 0.014GiB.
	Bucket 1 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
	Bucket 2 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
	Bucket 3 uniform sort. Ram: 4.441GiB, u_sort min: 0.055GiB, qs min: 0.014GiB.
	Bucket 4 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
	Bucket 5 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
	Bucket 6 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
	Bucket 7 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
	Bucket 8 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
	Bucket 9 uniform sort. Ram: 4.441GiB, u_sort min: 0.055GiB, qs min: 0.014GiB.
	Bucket 10 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
	Bucket 11 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
	Bucket 12 uniform sort. Ram: 4.441GiB, u_sort min: 0.055GiB, qs min: 0.014GiB.
	Bucket 13 uniform sort. Ram: 4.441GiB, u_sort min: 0.055GiB, qs min: 0.014GiB.
	Bucket 14 uniform sort. Ram: 4.441GiB, u_sort min: 0.055GiB, qs min: 0.014GiB.
	Bucket 15 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
	Total matches: 5194691
Caught exception: Matches do not match with number of write entries 5194691 5195139
terminate called after throwing an instance of 'std::exception'
  what():  std::exception
Aborted (core dumped)

```

**Comment by QuantumLiu** [comment]
> I tried to change FileDisk Write and Read to mapped IO, but got error.
> Do you have any idea to fix it?
> 
> ```
>     void Read(uint64_t begin, uint8_t *memcache, uint64_t length)
>     {
>         Open(retryOpenFlag);
> #if ENABLE_LOGGING
>         disk_log(filename_, op_t::read, begin, length);
> #endif
>         // Seek, read, and replace into memcache
>         if ((!bReading) || (begin != readPos)) {
> #ifdef _WIN32
>             _fseeki64(f_, begin, SEEK_SET);
> #else
>             // fseek() takes a long as offset, make sure it's wide enough
>             static_assert(sizeof(long) >= sizeof(begin));
>             ::fseek(f_, begin, SEEK_SET);
> #endif
>             bReading = true;
>         }
> 
>         uint64_t amtread=0;
>         int fd_i=fileno(f_);
>         struct stat fileInfo = {0};
>         if (fstat(fd_i, &fileInfo) == -1)
>         {
>             perror("Error getting the file size");
>             exit(EXIT_FAILURE);
>         }
>         
>         if (fileInfo.st_size == 0)
>         {
>             fprintf(stderr, "Error: File is empty, nothing to do\n");
>             exit(EXIT_FAILURE);
>         }
> 
> 
>         char *map = (char *)  mmap(NULL, length, PROT_READ, MAP_SHARED, fd_i, 0);
>         if (map == MAP_FAILED)
>         {
>             close(fd_i);
>             perror("Error mmapping the file");
>             exit(EXIT_FAILURE);
>         }
> 
>         
>         memcpy(memcache, map, length);
>         amtread+=length;
>         
>         // Don't forget to free the mmapped memory
>         if (munmap(map, length) == -1)
>         {
>             close(fd_i);
>             perror("Error un-mmapping the file");
>             exit(EXIT_FAILURE);
>         }
> 
>         readPos = begin + amtread;
>         if (amtread != length) {
>             std::cout << "Only read " << amtread << " of " << length << " bytes at offset "
>                         << begin << " from " << filename_ << "with length " << writeMax
>                         << ". Error " << ferror(f_) << ". Retrying in five minutes." << std::endl;
>             std::this_thread::sleep_for(5min);
>         }
> 
> 
>     }
> 
>     void Write(uint64_t begin, const uint8_t *memcache, uint64_t length)
>     {
>         Open(writeFlag | retryOpenFlag);
> #if ENABLE_LOGGING
>         disk_log(filename_, op_t::write, begin, length);
> #endif
>         // Seek and write from memcache
>         uint64_t amtwritten=0;
>         // do {
>             if ((bReading) || (begin != writePos)) {
> #ifdef _WIN32
>                 _fseeki64(f_, begin, SEEK_SET);
> #else
>                 // fseek() takes a long as offset, make sure it's wide enough
>                 static_assert(sizeof(long) >= sizeof(begin));
>                 ::fseek(f_, begin, SEEK_SET);
> #endif
>                 bReading = false;
>             }
>             uint64_t len=length+1;
>             int fd_o=fileno(f_);
> 
> 
>  
>             if (fd_o == -1)
>             {
>                 perror("Error opening file for writing");
>                 exit(EXIT_FAILURE);
>             }
> 
>             if (lseek(fd_o, len-1, SEEK_SET) == -1)
>             {
>                 close(fd_o);
>                 perror("Error calling lseek() to 'stretch' the file");
>                 exit(EXIT_FAILURE);
>             }
> 
>             if (write(fd_o, "", 1) == -1)
>             {
>                 close(fd_o);
>                 perror("Error writing last byte of the file");
>                 exit(EXIT_FAILURE);
>             }
> 
>             char *buffer = (char *) mmap(NULL, len, PROT_WRITE, MAP_SHARED, fd_o, 0);
> 
>             if (buffer == MAP_FAILED)
>             {
>                 close(fd_o);
>                 perror("Error mmapping the file");
>                 exit(EXIT_FAILURE);
>             }
>             
>             memcpy(buffer, memcache, len);
>             amtwritten += (len-1);
>             if (msync(buffer, len, MS_SYNC) == -1)
>             {
>                 perror("Could not sync the file to disk");
>             }
>             
>             // Don't forget to free the mmapped memory
>             if (munmap(buffer, len) == -1)
>             {
>                 close(fd_o);
>                 perror("Error un-mmapping the file");
>                 exit(EXIT_FAILURE);
>             }
> 
>             writePos = begin + amtwritten;
>             if (writePos > writeMax)
>                 writeMax = writePos;
>             if (amtwritten!= length) {
>                 std::cout << "Only wrote " << amtwritten << " of " << length << " bytes at offset "
>                           << begin << " to " << filename_ << "with length " << writeMax
>                           << ". Error " << ferror(f_) << ". Retrying in five minutes." << std::endl;
>                 std::this_thread::sleep_for(5min);
>             }
>         // } while (amtwritten != length);
>     }
> ```
> 
> The error LOG:
> 
> ```
> chiapos/build$ ./ProofOfSpace -k 25 -f "plot.dat"  create
> operation: create
> Generating plot for k=25 filename=plot.dat id=022fb42c08c12de3a6af053880199806532e79515f94e83461612101f9412f9e
> 
> 
> Starting plotting progress into temporary dirs: . and .
> ID: 022fb42c08c12de3a6af053880199806532e79515f94e83461612101f9412f9e
> Plot size is: 25
> Buffer size is: 4608MiB
> Using 16 buckets
> Using 2 threads of stripe size 65536
> 
> Starting phase 1/4: Forward Propagation into tmp files... Sat May  1 04:49:00 2021
> Computing table 1
> F1 complete, time: 2.018 seconds. CPU (105.68%) Sat May  1 04:49:02 2021
> Computing table 2
> 	Bucket 0 uniform sort. Ram: 4.441GiB, u_sort min: 0.055GiB, qs min: 0.014GiB.
> 	Bucket 1 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
> 	Bucket 2 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
> 	Bucket 3 uniform sort. Ram: 4.441GiB, u_sort min: 0.055GiB, qs min: 0.014GiB.
> 	Bucket 4 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
> 	Bucket 5 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
> 	Bucket 6 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
> 	Bucket 7 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
> 	Bucket 8 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
> 	Bucket 9 uniform sort. Ram: 4.441GiB, u_sort min: 0.055GiB, qs min: 0.014GiB.
> 	Bucket 10 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
> 	Bucket 11 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
> 	Bucket 12 uniform sort. Ram: 4.441GiB, u_sort min: 0.055GiB, qs min: 0.014GiB.
> 	Bucket 13 uniform sort. Ram: 4.441GiB, u_sort min: 0.055GiB, qs min: 0.014GiB.
> 	Bucket 14 uniform sort. Ram: 4.441GiB, u_sort min: 0.055GiB, qs min: 0.014GiB.
> 	Bucket 15 uniform sort. Ram: 4.441GiB, u_sort min: 0.027GiB, qs min: 0.014GiB.
> 	Total matches: 5194691
> Caught exception: Matches do not match with number of write entries 5194691 5195139
> terminate called after throwing an instance of 'std::exception'
>   what():  std::exception
> Aborted (core dumped)
> ```

I may find the problem.
5195139-5194691 =448=16x28=16x(1+2+3+4+6+7)
And there are 16 buckect and 7 table....

**Comment by InfuehrDaniel** [comment]
@QuantumLiu - Yeah i know whats wrong with your code. You use mmap for every read call this will be much slower! - The way its supposed to work is to have a memory range mapped into your virtual adress space. This is only needed ONCE and the details are handled by the OS for you. 

Also MAP_PRIVATE - is the right flag here. You are not sharing to other processes. Also std library std::copy is always optimal for memcpy. 

@QuantumLiu 
Can you move an application agnostic memmap handle to the constructor - and create a PR? You are almost there! **Literally all the code inside Read(uint64_t begin, uint8_t *memcache, uint64_t length) will be a one liner call to std::copy**

@arvidn 
**Beware** - Copying buffers should not be needed at all if memory mapped IO is implemented- only the ptr directly - so some refactoring is needed by the dev team to actually use memory mapped io correctly and get rid of the copy.

**Comment by arvidn** [comment]
chiapos is not a priority right now, but I'd be happy to review a PR though

**Comment by QuantumLiu** [comment]
> @QuantumLiu - Yeah i know whats wrong with your code. You use mmap for every read call this will be much slower! - The way its supposed to work is to have a memory range mapped into your virtual adress space. This is only needed ONCE and the details are handled by the OS for you.
> 
> Also MAP_PRIVATE - is the right flag here. You are not sharing to other processes. Also std library std::copy is always optimal for memcpy.
> 
> @QuantumLiu
> Can you move an application agnostic memmap handle to the constructor - and create a PR? You are almost there! *_Literally all the code inside Read(uint64_t begin, uint8_t _memcache, uint64_t length) will be a one liner call to std::copy__
> 
> @arvidn
> **Beware** - Copying buffers should not be needed at all if memory mapped IO is implemented- only the ptr directly - so some refactoring is needed by the dev team to actually use memory mapped io correctly and get rid of the copy.

Thank you so much.
But if memmap moved to the constructor , it may not handle read and write in one time? I'm still working on it.

**Comment by DmitriiWhy** [comment]
@QuantumLiu while implementing same feature I found issues with out of memory access. For example in a test entry_len is 6 bytes, but call to ExtractNum will end in EightBytesToInt which is:

uint64_t i;
memcpy(&i, bytes, sizeof(i));

bytes here is 6, sizeof(i) is 8

With allocated memory this might be not an issue, with mmap you will get access  violation. 

As  well I've found what  for some reason file size might be less than num_entries * entry_len and your mmap will run out of file size and crash as  result.

**Comment by arvidn** [comment]
we over-allocate by 7 bytes for this reason. So that would have to happen for mmap too probably. It's a lot faster to do that than to check for this condition every time we pull bits out of a buffer.

Another thing to consider is disk full or other I/O errors. See https://github.com/arvidn/try_signal

**Comment by Ed-Yang** [comment]
Hello,

I try to implement the mmap read cache, but it seems there is no much difference on my MacBook pro with a slow HDD.

If you are interested, you could help to review my branch and correct me if something is not doing well..

https://github.com/Ed-Yang/chiapos/tree/mmap

Thanks in advance.

**Comment by Jufik** [comment]
Tried this with `time ./ProofOfSpace -k 25 create` using Gen3 NVMes.

Main / mmap 

- Phase1: 59.007 s / 63.142 s
- Phase2: 8.374 s / 9 s
- Phase3 : 49.170 s / 48.766 s
- Phase4: 3.321 s / 3.133 s

Tried the experiment 3 times, does'nt get any obvious perf' improvement

**Comment by Ed-Yang** [comment]
In phase1, 2, it mostly perform write action, so the mmap is useless or introduce a little overhead.

In phase3, 4, original design implement a BufferDisk, seems the mmap shortcut in BufferDisk does not help much.

**Comment by InfuehrDaniel** [comment]
@Jufik what code did you use? mmap is only needed once - not for every read/write. Also this interface is not optimal - because you still need to copy from mmap to a buffer. with a mmap you dont need a buffer at all. The pointer = buffer = the whole 100gb file in your virtual memory space. The OS does lazy flush so its a lot faster. But not like implemented above. 


Yes mmap is also faster for writing to a file. What it cannot ever do is to increase a files size. But for chia this is not really needed. 
Since every 4kb or 64kb page is handled by the os there are no seek / read calls. So effectively 0 IO calls instead of 3 for every IO operations. 

Currently implemented: Seek -> Read -> Copy to buffer
Memory mapped IO: buffer already there = NOP

**Comment by Ed-Yang** [comment]
@InfuehrDaniel mmap just call once (in file open) not in every read/write.  For read function of FileDisk, I just replace from I/O call to memory copy from mapped memory.  But in BufferDisk, the read function does return a pointer not perform memory copy.

The mmap branch only implement a read cache and the write function is basically same as before.

FYI:
https://github.com/Ed-Yang/chiapos/tree/mmap

**Comment by arvidn** [comment]
> Yes mmap is also faster for writing to a file. What it cannot ever do is to increase a files size. But for chia this is not really needed.
> Since every 4kb or 64kb page is handled by the os there are no seek / read calls. So effectively 0 IO calls instead of 3 for every IO operations.
> 
> Currently implemented: Seek -> Read -> Copy to buffer
> Memory mapped IO: buffer already there = NOP

One thing to be aware of is that every page fault that is handled by the kernel is essentially a system call. You still get the context switch, and most likely a TLB flush. Every new page that's either:

1. to allocate a new page and ensure there's enough space on disk
2. fetch a new page from disk

Will be page faults handled by the kernel. Granted, this is something kernels are getting better at doing more efficiently, but it's not safe to assume that memory copying is the bottleneck of all I/O.

> Summary: Its a low hanging fruit

Can you show us your patch?

**Comment by arturzx** [comment]
I made changes in plotter to use SPDK (https://spdk.io), in brief:
"The bedrock of SPDK is a user space, polled-mode, asynchronous, lockless NVMe driver. This provides zero-copy, highly parallel access directly to an SSD from a user space application".

Tested with k=25 @ memory block driver and with k=32 @ Samsung PM983 NVMe, in both cases - zero time gain. Super light filesystem (BlobFS), no kernel mode - IMHO this shows that I/O is not problem with current plotting process.

Previous days I've tested plotting at tmpfs backed by swap on two NVMes - on first phase was ~20% gain but other phases was dramatically slower (I/O wait goes up) - probably by a lot of page faults.

**Comment by grayfallstown** [comment]
>  IMHO this shows that I/O is not problem with current plotting process.

@arturzx did you consider people plotting with sata ssds they already had laying around or even on rotational media? Being able to utilize Native Command Queuing on rotational disks through async reads/writes alone could make a big difference.

I plot on every drive I own, may it be nvme, sata-ssd or rotational as I already had the ram anyway.
