### ISSUE TITLE
CreatePlotDisk does not utilize tmp2 as an overflow

### ISSUE THREAD

**Issue by DavidLiuGit** [Chia-Network/chiapos#217]
## Background
When plotting, it is not readily apparent what "2nd temporary directory" (I'll refer to it as `tmp2`/`tmp2_dirname` here) is used for. Having looked into the code, I noticed that `tmp2` is only used starting in phase 3, when the plotter compresses intermediate data from phase 2 and writes it to `tmp2`. This behavior isn't well documented nor expected. The description in the GUI may mislead users into thinking `tmp2` is used as an overflow directory.

My attempt to plot using a 240GB NVMe SSD I had lying around gets stuck in phase 2, when `FileDisk.Write()` fails to write the entire file. The plotter spins infinitely in the `do ... while` loop of the `Write()` method.

## Proposal
utilize `tmp2`/`tmp2_dirname` in all phases as needed. In essence, implement functionality that would effectively use `tmp2` as an overflow if `FileDisk.Write()` fails due to hitting disk space limit (or for any other reason), in phase 1 & 2.

### Possible solution
`DiskPlotter.CreatePlotDisk()` constructs  `vector<FileDisk> tmp_1_filenames` based on `tmp_dirname` only. It may be feasible to:  
* construct `vector<FileDisk> tmp_2_overflow_filenames` using the same logic, but based on `tmp2_dirname`. This vector should be of the same size
* when calling `(b17)RunPhaseX()`, pass both `tmp_1_filenames` and `tmp_2_overflow_filenames`, possibly along with
* a simple data structure to track which filename was used/written

**Comment by hoffmang9** [comment]
The retry loop is intentional so that a user can remove space if they can but a 240GB is not large enough for the temp space of a k32.

**Comment by cvilasis69** [comment]
I think it is fine that the 'tmp2' folder was used as a temporary second level cache at the end of phases 1 & 2 because if 'tmp2' is in the same disk as 'dst' folder then the copy/move of contents are instantaneous.
It will be better to use an array of 'tmp' folders for the phases 1 & 2 with your proposal and don't touch 'tmp2'.

**Comment by emlowe** [comment]
Closing low-priority issue - we welcome any PRs
