### ISSUE TITLE
[Enhancement] Add a parameter to start a plot from a specified phase

### ISSUE THREAD

**Issue by graemes** [Chia-Network/chiapos#218]
It would be very useful to be able to restart a crashed or stopped plot from the end of a completed stage which has the tmp files available.  Have had a couple of crashes where I've managed to lose hours of plotting because I've had to restart from the beginning.  Unlikely IMO but could also be used to distributed different phases across different machines?

Perhaps -ph, --phase ?

**Comment by hoffmang9** [comment]
Pause/Resume is on the roadmap.
