### ISSUE TITLE
I put chiapos1.0.1 into chia-blockchian，but installed error

### ISSUE THREAD

**Issue by Hugh-Top** [Chia-Network/chiapos#229]
I put chiapos1.0.1 into chia-blockchian, but when I execute ‘python -m pip install ./chiapos-1.0.1’, an error occurs:

 LookupError: setuptools-scm was unable to detect version for '/opt/data/tmpf/pip-req-build-_2t868_b'.
  
  Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

This seems to be unable to find the .git folder, I want him to use the .git folder in the upper directory

**Comment by Chewbakka-Wakka** [comment]
You need to fetch it from here -> https://pypi.io/packages/source/c/chiapos/chiapos-1.0.2.tar.gz

**Comment by emlowe** [comment]
Closing issue
