### ISSUE TITLE
 Chia Blockchain 1.1.5  affect the plot of chiapos

### ISSUE THREAD

**Issue by Kayuii** [Chia-Network/chiapos#231]
Chia Blockchain 1.1.5  affect the plot of chiapos

**Comment by mariano54** [comment]
It doesn't affect plots. But it does affect your chances of farming a block.

**Comment by Kayuii** [comment]
May 17 new mine pool do I need replot? Or is it just about k32. Will chipos be updated on May 17?

**Comment by hoffmang9** [comment]
No tech support in Issues.
