### ISSUE TITLE
File transfers are very slow when final dir is a sshfs mount

### ISSUE THREAD

**Issue by flupke** [Chia-Network/chiapos#238]
I noticed file transfer tops at 1 MiB/s on my gigabit ethernet when a plot's final dir is a sshfs mount. I interrupted the plotting and copied the plot file with `cp` to the same sshfs mount, which gave me stable 120 MiB/s transfers as usual.

Also while `chia` was copying the plot, the mount was almost inaccessible, a simple `ls` would block for minutes. My guess is `fs::copy` must be writing in very small chunks to the destination.

**Comment by hoffmang9** [comment]
We intentionally give you the option of leaving the plot on your temp medium and using some other tool to move it off is standard C++ copy doesn't work for you.

**Comment by cayolblake** [comment]
> We intentionally give you the option of leaving the plot on your temp medium and using some other tool to move it off is standard C++ copy doesn't work for you.

@hoffmang9 Which command line parameter exactly does that?

**Comment by hoffmang9** [comment]
Set `-2` and `-d` to the same directory and use a tool to move all completed `.plot` files out of the `-2` directory.

**Comment by cayolblake** [comment]
Will try this today and confirm.

That should save me 6 minutes of copying when both temp and final are on the same mount point, on my NVMe backed storage.
