### ISSUE TITLE
Can create 1 plot, but the second one will always fail

### ISSUE THREAD

**Issue by Dajah74** [Chia-Network/chiapos#246]
Hello,

I have a i7 3770k which is and old CPU with 8go Ram

I have tried to create the plot accross the GUI or script but both always fail with the 2nd plot creation

I've made a simple script that will format the Temp SSD drive before creating the 2nd plot but this didnt help at all

function plot{
    if ($i -eq 0){
    Write-host "Work Done"
    }else{
    $i
    Format-Volume -DriveLetter G -FileSystem NTFS -NewFileSystemLabel CHIA_SSD
    cd $env:USERPROFILE\AppData\Local\Chia-Blockchain\app*\resources\app.asar.unpacked\daemon
    .\chia.exe version
    .\chia.exe plots create -k 32 -n 1 -t "G:\" -d "H:\" -b 3389 -u 128 -r 2
    $i--
    plot
    }
}
$i=6 #set the nb of plot you want to create
plot

You can see my plot settings in the scripts :
.\chia.exe plots create -k 32 -n 1 -t "G:\" -d "H:\" -b 3389 -u 128 -r 2

The error is every time the same : 
Only wrote * bytes at * with length * . Error 1. Retrying in five minutes.

I'm running Windows 10 and my FileSystem is NTFS, Memtest tell me everything is ok.

What should I do ? 

I can continue to grow my farm doing 1 plot after 1, but it's not really powerfull :/

Thanks for reading

ADD: I see that k32 need 239GiB and my SSD space is 238Go
I have not enough space then ? Cause > 239 GiB = 256.624295936 GB
But why can I create 1 plot, but not 2... I'm lost

**Comment by emlowe** [comment]
Closing issue
