### ISSUE TITLE
BUG: Build Fails - Version 1.0.2.  Errors during compile in catch.hpp 

### ISSUE THREAD

**Issue by Chewbakka-Wakka** [Chia-Network/chiapos#252]
Scanning dependencies of target RunTests
[ 30%] Building CXX object CMakeFiles/RunTests.dir/tests/test-main.cpp.o
In file included from /usr/include/signal.h:315,
                 from /home/ss/rpmbuild/BUILD/chiapos-1.0.2/tests/../lib/include/catch.hpp:8034,
                 from /home/ss/rpmbuild/BUILD/chiapos-1.0.2/tests/test-main.cpp:16:
/home/ss/rpmbuild/BUILD/chiapos-1.0.2/tests/../lib/include/catch.hpp:10822:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
10822 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/bits/sigstksz.h:24,
                 from /usr/include/signal.h:315,
                 from /home/ss/rpmbuild/BUILD/chiapos-1.0.2/tests/../lib/include/catch.hpp:8034,
                 from /home/ss/rpmbuild/BUILD/chiapos-1.0.2/tests/test-main.cpp:16:
/usr/include/unistd.h:630:17: note: ‘long int sysconf(int)’ declared here
  630 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
In file included from /home/ss/rpmbuild/BUILD/chiapos-1.0.2/tests/test-main.cpp:16:
/home/ss/rpmbuild/BUILD/chiapos-1.0.2/tests/../lib/include/catch.hpp:10881:45: error: size of array ‘altStackMem’ is not an integral constant-expression
10881 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~

**Comment by Chewbakka-Wakka** [comment]
Same errors in 1.0.3

**Comment by emlowe** [comment]
Closing issue
