### ISSUE TITLE
Minor Feature Req - Plotting K=25 remove from GUI

### ISSUE THREAD

**Issue by Chewbakka-Wakka** [Chia-Network/chiapos#253]
Users can still select Plot size of K=25 ... which does not qualify for farming on the mainnet

K=32 is the min. 

I suppose for testing maybe but you may want to add some disclaimer when this is chosen

**Comment by hoffmang9** [comment]
There is already a modal dialog box. Did you not receive it?

**Comment by emlowe** [comment]
Closing issue - there is a warning dialog you must click through
