### ISSUE TITLE
fails to build on osx not detecting instructions correctly

### ISSUE THREAD

**Issue by Hardcore-fs** [Chia-Network/chiapos#260]
tests build fails, but it works on a linux VM inside the SAME computer
build tools ?

```
cmake --build . -- -j 6
[  2%] Building CXX object CMakeFiles/uint128.dir/uint128_t/uint128_t.cpp.o
[  6%] Building CXX object _deps/cxxopts-build/test/CMakeFiles/link_test.dir/link_b.cpp.o
[  9%] Building CXX object _deps/cxxopts-build/test/CMakeFiles/options_test.dir/main.cpp.o
[  9%] Building CXX object _deps/cxxopts-build/test/CMakeFiles/link_test.dir/link_a.cpp.o
[ 13%] Building CXX object _deps/cxxopts-build/src/CMakeFiles/example.dir/example.cpp.o
[ 13%] Building C object CMakeFiles/fse.dir/lib/FiniteStateEntropy/lib/fse_compress.c.o
[ 16%] Building C object CMakeFiles/fse.dir/lib/FiniteStateEntropy/lib/fse_decompress.c.o
[ 18%] Building C object CMakeFiles/fse.dir/lib/FiniteStateEntropy/lib/entropy_common.c.o
[ 20%] Building C object CMakeFiles/fse.dir/lib/FiniteStateEntropy/lib/hist.c.o
[ 23%] Linking C static library libfse.a
[ 23%] Built target fse
[ 25%] Building CXX object _deps/cxxopts-build/test/CMakeFiles/options_test.dir/options.cpp.o
[ 27%] Linking CXX static library libuint128.a
[ 27%] Built target uint128
Scanning dependencies of target chiapos
[ 30%] Building CXX object CMakeFiles/chiapos.dir/python-bindings/chiapos.cpp.o
Scanning dependencies of target ProofOfSpace
[ 32%] Linking CXX executable link_test
[ 34%] Building CXX object CMakeFiles/ProofOfSpace.dir/src/cli.cpp.o
[ 34%] Built target link_test
[ 37%] Building C object CMakeFiles/chiapos.dir/src/chacha8.c.o
[ 39%] Building C object CMakeFiles/ProofOfSpace.dir/src/chacha8.c.o
[ 41%] Building C object CMakeFiles/ProofOfSpace.dir/src/b3/blake3.c.o
[ 44%] Building C object CMakeFiles/chiapos.dir/src/b3/blake3.c.o
Scanning dependencies of target RunTests
[ 46%] Building CXX object CMakeFiles/RunTests.dir/tests/test-main.cpp.o
[ 48%] Linking CXX executable example
[ 48%] Built target example
[ 51%] Building C object CMakeFiles/chiapos.dir/src/b3/blake3_portable.c.o
[ 53%] Building C object CMakeFiles/chiapos.dir/src/b3/blake3_dispatch.c.o
[ 55%] Building ASM object CMakeFiles/chiapos.dir/src/b3/blake3_avx2_x86-64_unix.S.o
[ 58%] Building ASM object CMakeFiles/chiapos.dir/src/b3/blake3_avx512_x86-64_unix.S.o
/Volumes/null/shitpos/chiapos/src/b3/blake3_avx512_x86-64_unix.S:29:9: error: instruction requires: AVX-512 ISA
        kmovw k1, r9d
        ^
```

**Comment by arvidn** [comment]
what does `uname -m` print for you?

**Comment by Hardcore-fs** [comment]
I managed to get it working  with a little bit of hacking.....
it is failing in "blake3_dispatch.c",

I suspect becasue it is only tested for x86_64, then it falls thru the "else"
but this excludes a large number of fairly recent computers as well, some osx models only 3 years old.

uname -m
x86_64

there is fall back code, it's just not being selected correctly.

**Comment by Hardcore-fs** [comment]
you know what is absolutely crazy......

is that if i open a  linux vm on the same machine

uname -m
x86_64

and yet it compiles and it works!!!

**Comment by arvidn** [comment]
> I suspect becasue it is only tested for x86_64, then it falls thru the "else"
> but this excludes a large number of fairly recent computers as well, some osx models only 3 years old.

It works on Apple M1, which is `arm64`, but you're right that there's no check for x86 specifically, we just assume that if it isn't windows or arm64 it must be x86. To be fair though, that is a correct guess in your case.

> uname -m
> x86_64
> 
> there is fall back code, it's just not being selected correctly.

I'm pretty sure the fall back code is meant to be selected at run-time. For some reason your *assembler* fails to turn assembly code into machine code, for AVX-512 instructions. That's a bit puzzling. I bet the assembler on Linux does that without checking which host it's running on.

I'm pretty sure this works on my x86 Mac as well (but it's not handy and set up to try again right now).

Maybe you can look into which version of the development tools you have installed. Maybe the default behavior changed recently to only assemble code that runs on the host machine.

**Comment by Hardcore-fs** [comment]
not puzzling at all....
as i  pointed out, not all cpu have AVX-512 instructions.
the reason the arm passes, is that it specifically has "arm" libraries that do not employ avx-512 instructions.
more recent macs as in the last 1-2 years have avx-512 instructions.

and i'm not convinced about the argument on "CMakeList.txt" , where it deals with AVX-512 becasue it is forced.

since that would not cover the fact that it can compile on a linux vm on a computer WITHOUT avx-512 instructions.
if i could upgrade my CPU just by running a VM, why by new cpu's?

**Comment by Hardcore-fs** [comment]
possibly adding a flag in  "CMakeList.txt" ,  crapple_avx-512=0, then force it to use the source that doesn't even have the avx-512 instructions.
but the blake3 libraries build absolutely no problem on the same osx platform, so they clearly have a stronger detection system.

**Comment by arvidn** [comment]
> not puzzling at all....
> as i pointed out, not all cpu have AVX-512 instructions.

But the program that turns assembly code into machine code (the "assembler") doesn't need AVX-512 instructions to do so. For example, the assembler on linux doesn't.

> since that would not cover the fact that it can compile on a linux vm on a computer WITHOUT avx-512 instructions.
> if i could upgrade my CPU just by running a VM, why by new cpu's?

The command that's failing is invoking the assembler to turn AVX-512 assembly code (text) into machine code. It's not failing because it's trying to *execute* such instructions. Presumably there's some "safety" mechanism that tells you that you won't be able to run the resulting binary on your machine.

I would guess that there's some flag that needs to be passed to the assembler on OSX to generate the machine code anyway. or possibly there's some flag that's being passed now (something like `-march=native`) that we are not allowed to pass.

Can you make `cmake` print the command line that's failing?

**Comment by Hardcore-fs** [comment]
In the real world..... yes but maybe in the crapple world.....
they DELIBERATELY built certain versions of xcode that could not use avx-512, becasue none of their  CPU had it.
so developers could not do something stupid....
then.. suddenly they started to ship CPU with avx-512 instructions , so they enables that  mnemonic translation in xcode.
(think 10.15/big sur) n

cmake i presume you mean 

`
[ 46%] Building ASM object CMakeFiles/ProofOfSpace.dir/src/b3/blake3_sse41_x86-64_unix.S.o
/Library/Developer/CommandLineTools/usr/bin/cc  -I/Volumes/null/shitpos/chiapos/../lib/include -I/Volumes/null/shitpos/chiapos/build/_deps/cxxopts-src/include -I/Volumes/null/shitpos/chiapos/build/_deps/gulrak-src/include/ghc -I/Volumes/null/shitpos/chiapos/../lib/FiniteStateEntropy/lib -I/Volumes/null/shitpos/chiapos/src -I/Volumes/null/shitpos/chiapos/test -O3 -DNDEBUG -fPIE -o CMakeFiles/ProofOfSpace.dir/src/b3/blake3_avx512_x86-64_unix.S.o -c /Volumes/null/shitpos/chiapos/src/b3/blake3_avx512_x86-64_unix.S
/Library/Developer/CommandLineTools/usr/bin/cc -Dchiapos_EXPORTS -I/Volumes/null/shitpos/chiapos/../lib/include -I/Volumes/null/shitpos/chiapos/build/_deps/cxxopts-src/include -I/Volumes/null/shitpos/chiapos/build/_deps/gulrak-src/include/ghc -I/Volumes/null/shitpos/chiapos/../lib/FiniteStateEntropy/lib -I/Volumes/null/shitpos/chiapos/src -I/Volumes/null/shitpos/chiapos/test -isystem /Volumes/null/shitpos/chiapos/build/_deps/pybind11-src-src/include -isystem /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -O3 -Wall -g -O3 -DNDEBUG -fPIC -MD -MT CMakeFiles/chiapos.dir/src/b3/blake3.c.o -MF CMakeFiles/chiapos.dir/src/b3/blake3.c.o.d -o CMakeFiles/chiapos.dir/src/b3/blake3.c.o -c /Volumes/null/shitpos/chiapos/src/b3/blake3.c
/Library/Developer/CommandLineTools/usr/bin/cc -Dchiapos_EXPORTS -I/Volumes/null/shitpos/chiapos/../lib/include -I/Volumes/null/shitpos/chiapos/build/_deps/cxxopts-src/include -I/Volumes/null/shitpos/chiapos/build/_deps/gulrak-src/include/ghc -I/Volumes/null/shitpos/chiapos/../lib/FiniteStateEntropy/lib -I/Volumes/null/shitpos/chiapos/src -I/Volumes/null/shitpos/chiapos/test -isystem /Volumes/null/shitpos/chiapos/build/_deps/pybind11-src-src/include -isystem /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -O3 -Wall -g -O3 -DNDEBUG -fPIC -MD -MT CMakeFiles/chiapos.dir/src/chacha8.c.o -MF CMakeFiles/chiapos.dir/src/chacha8.c.o.d -o CMakeFiles/chiapos.dir/src/chacha8.c.o -c /Volumes/null/shitpos/chiapos/src/chacha8.c
/Library/Developer/CommandLineTools/usr/bin/cc  -I/Volumes/null/shitpos/chiapos/../lib/include -I/Volumes/null/shitpos/chiapos/build/_deps/cxxopts-src/include -I/Volumes/null/shitpos/chiapos/build/_deps/gulrak-src/include/ghc -I/Volumes/null/shitpos/chiapos/../lib/FiniteStateEntropy/lib -I/Volumes/null/shitpos/chiapos/src -I/Volumes/null/shitpos/chiapos/test -O3 -DNDEBUG -fPIE -o CMakeFiles/ProofOfSpace.dir/src/b3/blake3_sse41_x86-64_unix.S.o -c /Volumes/null/shitpos/chiapos/src/b3/blake3_sse41_x86-64_unix.S
[ 48%] Building ASM object CMakeFiles/RunTests.dir/src/b3/blake3_avx512_x86-64_unix.S.o
/Library/Developer/CommandLineTools/usr/bin/cc  -I/Volumes/null/shitpos/chiapos/../lib/include -I/Volumes/null/shitpos/chiapos/build/_deps/cxxopts-src/include -I/Volumes/null/shitpos/chiapos/build/_deps/gulrak-src/include/ghc -I/Volumes/null/shitpos/chiapos/../lib/FiniteStateEntropy/lib -I/Volumes/null/shitpos/chiapos/src -I/Volumes/null/shitpos/chiapos/test -O3 -DNDEBUG -fPIE -o CMakeFiles/RunTests.dir/src/b3/blake3_avx512_x86-64_unix.S.o -c /Volumes/null/shitpos/chiapos/src/b3/blake3_avx512_x86-64_unix.S
/Volumes/null/shitpos/chiapos/src/b3/blake3_avx512_x86-64_unix.S:29:9: /Volumes/null/shitpos/chiapos/src/b3/blake3_avx512_x86-64_unix.Serror: :29instruction requires: AVX-512 ISA:9
: error: instruction requires: AVX-512 ISA 
             k m okvmwo vkw1 ,k 1r,9 dr
9d 
             ^ 
 ^
/Volumes/null/shitpos/chiapos/src/b3/blake3_avx512_x86-64_unix.S:39:9: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
        vpcmpltud k2, ymm2, ymm0
`

**Comment by arvidn** [comment]
> they DELIBERATELY built certain versions of xcode that could not use avx-512, becasue none of their CPU had it.
> so developers could not do something stupid....
> then.. suddenly they started to ship CPU with avx-512 instructions , so they enables that mnemonic translation in xcode.
> (think 10.15/big sur) n

Do you think it would work if you'd run the most recent version of xcode? or are you already?

**Comment by Hardcore-fs** [comment]
it is a complex issue.....
This is ALL relevant becasue of apples "code signing", you cannot just load in the latest xcode, even if you  hack the version support numbers.

I have access to about 40 macs and results vary...
the best solution is a flag, 
The code is already in the files, i reliably built "chiapos ",simply by  commenting out certain files.

but ultimately who cares about apple users right?
it's an interesting diversion... nothing more.... lets face it , i nearly set a mac pro on fire running this...
the batteries ballooned becasue the cpu heat sink could not dump fast enough...
so much so the back burst off  the computer....
(the joys of having corporate macs to trash)

**Comment by noisymime** [comment]
This looks like the same thing I raised in #219 . The AVX512 specific assembler code really should be wrapped in `#ifdef` guards that exclude the code if the CPU doesn't support it, regardless of whether it will ever get called at runtime or not. 

I do get the point that it will never be executed, but given how much of the other blake3 code is laid out, it would make sense for the assembler to not even include these instructions on CPUs that don't support them.

**Comment by emlowe** [comment]
Closing issue - I'm able to build without modifications on macOS 10.14 on a SandyBridge-EP processor that has AVX but not AVX2 or others and on macOS 10.15 on i7-3840QM also with AVX but not anything else.
