### ISSUE TITLE
./HellmanAttacks

### ISSUE THREAD

**Issue by MontajnikRTA** [Chia-Network/chiapos#261]
Good afternoon to all. I can't find how to run ./HellmanAttacks. I would be grateful for clarification on how to run and how it works.

**Comment by wjblanke** [comment]
The Hellman attacks codebase is really out of date. It really should only be used as a reference at this point, it may take some work to get it running again.

**Comment by MontajnikRTA** [comment]
> Кодовая база атак Хеллмана действительно устарела. На данный момент его действительно следует использовать только в качестве справки, может потребоваться некоторая работа, чтобы снова запустить его.

Can you tell me which commands to use to start, where to get instructions?
