### ISSUE TITLE
improvement to instructions for completeness

### ISSUE THREAD

**Issue by Hardcore-fs** [Chia-Network/chiapos#263]
small point on instructions
currently is shows:

`# Requires cmake 3.14+

mkdir -p build && cd build
cmake ../
cmake --build . -- -j 6`

it might be better shown as:

`# Requires cmake 3.14+
cd chiapos

mkdir -p build && cd build

cmake ../

cmake --build . -- -j 6`

**Comment by SippieCup** [comment]
Most instructions on Github assume the starting directory location to be the root of the repository.

It would be hard to give any instructions otherwise as people can save things anywhere.

**Comment by Hardcore-fs** [comment]
hi,
 maybe you missed my  point, the starting  directory is irrelevant.
the fact is that "build" has to go inside "chiapos"
after a git clone you are outside the directory

`Macpro-5-1:/ steve$ sudo -i
Password:

For troubleshooting assistance, just type 'applejack' at the prompt
Macpro-5-1:~ root# cd /
Macpro-5-1:/ root# git clone https://github.com/Chia-Network/chiapos.git
Cloning into 'chiapos'...
remote: Enumerating objects: 2728, done.
remote: Counting objects: 100% (2315/2315), done.
remote: Compressing objects: 100% (764/764), done.
remote: Total 2728 (delta 1539), reused 2144 (delta 1428), pack-reused 413
Receiving objects: 100% (2728/2728), 2.69 MiB | 9.04 MiB/s, done.
Resolving deltas: 100% (1646/1646), done.
Macpro-5-1:/ root# mkdir -p build && cd build
Macpro-5-1:build root# cmake ../
CMake Error: The source directory "/" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Macpro-5-1:build root# `

with added cd...

`cd ..
Macpro-5-1:/ root# rm -rf build
Macpro-5-1:/ root# cd chiapos
Macpro-5-1:chiapos root# mkdir -p build && cd build
Macpro-5-1:build root# cmake ../
-- The C compiler identification is AppleClang 10.0.0.10001044
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- The ASM compiler identification is AppleClang
-- Found assembler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
^C
etc.....`

**Comment by SippieCup** [comment]
You are trying to build in `/` not in /chiapos (also, why are you building it there?)

The assumption that instructions start at the root of the repository is 100% standard. it assumes that you have cloned and are within the chiapos directory already.

**Comment by Hardcore-fs** [comment]
because i'm following the instructions as written.....
what i was proposing is a change to make sure  builders were in teh correct directory.

**Comment by emlowe** [comment]
Closing issue
