### ISSUE TITLE
uniformsort.hpp possible bug (or not)

### ISSUE THREAD

**Issue by orryon** [Chia-Network/chiapos#268]
uniformsort.hpp, lines 74 and 83
`

        while (!IsPositionEmpty(memory + pos, entry_len) && pos < memory_len) {
          ...
        // Push the entry in the first free spot.
        memcpy(memory + pos, buffer.get() + buf_ptr, entry_len);

`
are you sure that you'll never leave the while() with pos == memory_len ?
probably ever the page fault exception will not be raised if the next memory addresses is allocated too (i didn't see the guard page request after the allocated memory).
i think it's possible that if pos == memory_len you will lose this item and it will overwrite some data beyond the memory array end, doesn't it ?

**Comment by SippieCup** [comment]
No, pos is the start of an entry, which reads to a certain length. memory_len is the total length of all the entries.

If pos >= memory_len you have made a mistake earlier on and have an off-by-one error and would be reading uninitialized space. there cannot be any relevant data at that location, so no item would be "lost"
