### ISSUE TITLE
[BUG] Harvester crashes with socket error after couple of hours

### ISSUE THREAD

**Issue by SebastianMetzger** [Chia-Network/chiapos#269]
**Describe the bug**
Sometimes I find one my harvesters not talking to the farmer anymore.
This happened now several times on different machines in the last couple of days. Including Ubunut Server, Ubuntu Desktop and a raspberry pie with raspbian.
I updated to chia 1.0.5 on all devieces over the last couple of days.

**To Reproduce**
Run the harvester and wait couple of days/hours until it stops connecting to the farmer

**Expected behavior**
The harvester to continue harvesting :) 
When such an error occurs, it should at least restart itself. 
Will probably write a script in the short term that restarts the harvester regularly.

**Screenshots**
07:19:29.127 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sebastian/chia-blockchain/chia/daemon/server.py", line 165, in safe_handle
    async for message in websocket:
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/sebastian/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**Desktop (please complete the following information):**

- OS: Ubuntu Desktop, Ubuntu Server, Raspbian
- OS Version/Flavor: Ubuntu 20.04., Raspbian 64bit
- CPU: Different

**Additional context**
I can retrieve more info from the different machines, but as it seems to appear radomly everywhere, might be a genearal thing?
Happens with LAN connection at home, data center LAN and WiFi at home

**Comment by arvidn** [comment]
do we save debug symbols for these builds?

**Comment by laszlojanosek** [comment]
The problem persists after a full reboot. I am out of ideas, find it difficult to debug further without compromising farming operation. The next viable step is the reinstallation of the OS. But this brings the question if Ubuntu 20.04 is really the right platform to run chia farm 24/7. Or the problem is with a hardware component or compatibility issue? Cannot find a clear indication from my logs. 

It would help if someone confirms similar issues, so we could compare.

**Comment by hoffmang9** [comment]
The odds are that you have a bad plot. We consider this still an issue as we want harvester to survive bad plots. Ubuntu 20.04 is where most all development and testing is done currently so it's not your OS.

**Comment by laszlojanosek** [comment]
I started the farming on an older WS, first on Windows than Ubuntu. Run up to 1.1.5 without issues other than limited hardware resources to grow. As soon as 1.1.6 came out I moved over to a new platform, fresh install. Carefully migrated the approx 2000 plots to the new drives (from NTFS to ext4), mixed of SATA/SAS & some USB3. My MB is ASUS Z590-A, which BIOS I did not calibrate, left mostly on default/AUTO.
I had two crashes in the morning (7 am and 10 am) after I decided to limit the DRAM freq. from AUTO (2900) to 2600. So far no segmentation fault. 

I just started "chia plots check" if it finds any bad plots and I keep on running standard farm/plotting ops. I will update here if anything changes.

**Comment by laszlojanosek** [comment]
> The odds are that you have a bad plot. We consider this still an issue as we want harvester to survive bad plots. Ubuntu 20.04 is where most all development and testing is done currently so it's not your OS.

Thanks for the hint about bad plots. Indeed, after several days of struggle and reinstallations, I can confirm the segfault issues were due to some faulty plots found using CLI. Since I got rid of those the farmer is working stable (24+hrs so far). I created watchdogs to regularly check and report if a plot faults. I understand the solution is to make harvester able to discover and automatically skip these. Thanks again for the support.

**Comment by laszlojanosek** [comment]
> Did you happen to save one of the bad plots?

Unfortunately not. As I think about it now it was a mistake to script it in a way to remove any plots either reported an error or the challenge value was below 0.7. But I desperately wanted to get rid of any potential problem as my harvester crashed so frequently. I even missed adding logging to the script or save the console output. I remember it was 6 plots out of 2200+ was bad and some of those sizes were odd. Slightly bigger than the normal ones (109/107 GB). What could happen is I corrupted the files while I moved them over from my old harvester. I tried different techniques (cpio/rsync/tar, with ionice/nice, and anything I could get) to reduce the impact on the target drives. It took me some days to realize I should just suffer the consequences and ignore the "Looking up qualities" errors while the transfer completes. 
Sorry I could not be much of a help. I know it for next time if I find any bad plot I will provide it and record logs more carefully.

**Comment by hoffmang9** [comment]
Don't worry. It's on me for not thinking to mention that.

**Comment by laszlojanosek** [comment]
> Did you happen to save one of the bad plots?

Found one of the bad plots which I renamed before I run the script to clean up. I can upload to Onedrive but I need an email I can share with. I rather not go full public with it. Happen to have storage I can upload to or send me an email address I can share the file with please let me know.

**Comment by emlowe** [comment]
Apologies for the delay in responding - if you still have this plot and can still upload to Onedrive - you can send an invite to e.lowe@chia.net

**Comment by St3ffn** [comment]
This issue might be related to [3367](https://github.com/Chia-Network/chia-blockchain/issues/3367)

**Comment by SebastianMetzger** [comment]
FYI, upgraded to latest version 1.2.2 and the issue still occurs.
Probably related to errors about corrupted plots  I also have in the plots from time to time ?

**Comment by buglantiss** [comment]
same issue on 1.2.2, chia_harvester still crashes with segfault

**Comment by arvidn** [comment]
Maybe we should log plot id and the challenge before each proof lookup to help reproduce these crashes

**Comment by djjaeger82** [comment]
When can we get a fix for this?  Been an ongoing issue for months on chia and forks.

**Comment by nagakong** [comment]
having this issue as well, waiting for more information on what to fix or what to do
