### ISSUE TITLE
Possible bug in phase 2 -> table 7

### ISSUE THREAD

**Issue by FilixDark** [Chia-Network/chiapos#273]
We were going to the code, and it seems table 7 is also using a buffered disk, but in the end, the last cache is not flushed.

All flushing is done here:

```
if (table_index != 7) {
            sort_manager->FlushCache();
            sort_timer.PrintElapsed("sort time = ");

            // clear disk caches
            disk.FreeMemory();
            sort_manager->FreeMemory();

            output_files[table_index - 2] = std::move(sort_manager);
            new_table_sizes[table_index] = write_counter;
        }
```

I checked everywhere if I can see anything that would flush the remaining content of a write buffer, couldn't find anything.

**Comment by grayfallstown** [comment]
Not a C++ developer but aren't stream flushed on close, closed in the destructor and the destructor is called when the variable runs out of context (unless its a pointer)?

**Comment by FilixDark** [comment]
well they wrote their own buffered disk, and keep it in memory, so they are not giving it to any real file stream at that point.
