### ISSUE TITLE
Small perf improvement in uniformsort

### ISSUE THREAD

**Issue by mgraczyk** [Chia-Network/chiapos#274]
I think you can do something like this for a small performance improvement in uniformsort

![image](https://user-images.githubusercontent.com/1097264/120701000-397b7580-c467-11eb-8169-d40794f44044.png)

**Comment by grayfallstown** [comment]
Can you create and provide a benchmark comparing the solutions?

**Comment by mgraczyk** [comment]
This and my other changes decrease the time to sort ~270MB by around 35%

![image](https://user-images.githubusercontent.com/1097264/120709991-71d48100-c472-11eb-8d84-8e2454f70421.png)

**Comment by arvidn** [comment]
@mgraczyk would you mind submitting your patch as a PR?
That would make it easier to review and for other people to test and benchmark

**Comment by BIG-BELL-CHEN** [comment]
I tested this optimization with 57 servers and the results were not very satisfactory. @mgraczyk  @arvidn 
1.03 main
![10171623130167_ pic_hd](https://user-images.githubusercontent.com/67949056/121128322-cc4c5380-c85d-11eb-8f3e-326c844ce8f4.jpg)
Your branch #276 
![10181623130185_ pic_hd](https://user-images.githubusercontent.com/67949056/121128382-e25a1400-c85d-11eb-9091-83e4e40e999f.jpg)

**Comment by emlowe** [comment]
Closing issue based on closed PR and testing results
