### ISSUE TITLE
I have an idea. I can calculate all the data of winner through the database

### ISSUE THREAD

**Issue by try2020-code** [Chia-Network/chiapos#277]
I have an idea that I can calculate all the data of winner through database storage, so that all my p disk files can be stored offline. I don't know if this idea is feasible. I mean when I read the complete plot file, I want to save other information in the database. When I really need to read the complete plot file, I insert the corresponding hard disk. I want to know if it can be realized, How much information does each k32 file need to store in the database to meet my needs

**Comment by hoffmang9** [comment]
It is designed to not allow this. You must use storage that is faster than a tape robot.
