### ISSUE TITLE
Bucket sorting in RAM - less SSD usage and electronic waste

### ISSUE THREAD

**Issue by DVLP** [Chia-Network/chiapos#288]
Not only electricity usage is important but also reducing electronic waste so to make Chia actually green it should not be going through SSDs so fast. On PCs with 256GB or more it can be made possible by doing the whole bucket sorting in memory hugely reducing SSD usage per plot and it's ~30% faster too. I've been working on the prototype for a few weeks and it finally produces valid plots https://github.com/DVLP/chiapos

**Comment by llamasoft** [comment]
If you have over 256 GB of RAM then you don't need to make code changes for this.  Just mount a memory-backed tmpfs and use that as your temp directory.

If I'm being honest, this seems like less of an issue with chiapos and more of a way for you to promote your project.

**Comment by DVLP** [comment]
Mounting a drive is at least 30% slower
