### ISSUE TITLE
Build failed...

### ISSUE THREAD

**Issue by YunL0ngLee** [Chia-Network/chiapos#289]
Scanning dependencies of target ProofOfSpace
[ 37%] Building CXX object CMakeFiles/ProofOfSpace.dir/src/cli.cpp.o
In file included from /home/min/work/chiapos/tests/test.cpp:22:0:
/home/min/work/chiapos/src/disk.hpp: In member function ‘void FileDisk::Read(uint64_t, uint8_t*, uint64_t)’:
/home/min/work/chiapos/src/disk.hpp:167:60: error: expected ‘,’ before ‘)’ token
                 static_assert(sizeof(long) >= sizeof(begin));
                                                            ^
/home/min/work/chiapos/src/disk.hpp:167:60: error: expected string-literal before ‘)’ token
/home/min/work/chiapos/src/disk.hpp: In member function ‘void FileDisk::Write(uint64_t, const uint8_t*, uint64_t)’:
/home/min/work/chiapos/src/disk.hpp:202:60: error: expected ‘,’ before ‘)’ token
                 static_assert(sizeof(long) >= sizeof(begin));
                                                            ^
/home/min/work/chiapos/src/disk.hpp:202:60: error: expected string-literal before ‘)’ token
In file included from /home/min/work/chiapos/src/sort_manager.hpp:30:0,
                 from /home/min/work/chiapos/src/phase1.hpp:45,
                 from /home/min/work/chiapos/src/plotter_disk.hpp:41,
                 from /home/min/work/chiapos/tests/test.cpp:23:
/home/min/work/chiapos/src/./uniformsort.hpp: At global scope:
/home/min/work/chiapos/src/./uniformsort.hpp:29:26: error: ‘UniformSort::BUF_SIZE’ declared as an ‘inline’ variable
     inline int64_t const BUF_SIZE = 262144;
                          ^
In file included from /home/min/work/chiapos/src/plotter_disk.hpp:41:0,
                 from /home/min/work/chiapos/tests/test.cpp:23:
/home/min/work/chiapos/src/phase1.hpp: In function ‘void* phase1_thread(THREADDATA*)’:
/home/min/work/chiapos/src/phase1.hpp:401:37: error: expected unqualified-id before ‘[’ token
                         const auto& [L_entry, R_entry, f_output] = current_entries_to_write[i];
                                     ^
/home/min/work/chiapos/src/phase1.hpp:401:37: error: expected initializer before ‘[’ token
/home/min/work/chiapos/src/phase1.hpp:404:77: error: ‘f_output’ was not declared in this scope
                         Bits new_entry = table_index + 1 == 7 ? std::get<0>(f_output).Slice(0, k)
                                                                             ^
/home/min/work/chiapos/src/phase1.hpp:412:48: error: ‘L_entry’ was not declared in this scope
                                 L_position_map[L_entry.pos % position_map_size] + L_position_base;
                                                ^
/home/min/work/chiapos/src/phase1.hpp:415:48: error: ‘L_entry’ was not declared in this scope
                                 R_position_map[L_entry.pos % position_map_size] + R_position_base;
                                                ^
/home/min/work/chiapos/src/phase1.hpp:417:50: error: ‘R_entry’ was not declared in this scope
                         newrpos = R_position_map[R_entry.pos % position_map_size] + R_position_base;
                                                  ^
In file included from /home/min/work/chiapos/src/phase2.hpp:22:0,
                 from /home/min/work/chiapos/src/plotter_disk.hpp:42,
                 from /home/min/work/chiapos/tests/test.cpp:23:
/home/min/work/chiapos/src/bitfield_index.hpp: At global scope:
/home/min/work/chiapos/src/bitfield_index.hpp:24:48: error: ‘kIndexBucket’ declared as an ‘inline’ field
     static inline const int64_t kIndexBucket = 1024;
                                                ^
In file included from /home/min/work/chiapos/src/sort_manager.hpp:28:0,
                 from /home/min/work/chiapos/src/phase1.hpp:45,
                 from /home/min/work/chiapos/src/plotter_disk.hpp:41,
                 from /home/min/work/chiapos/src/cli.cpp:20:
/home/min/work/chiapos/src/./disk.hpp: In member function ‘void FileDisk::Read(uint64_t, uint8_t*, uint64_t)’:
/home/min/work/chiapos/src/./disk.hpp:167:60: error: expected ‘,’ before ‘)’ token
                 static_assert(sizeof(long) >= sizeof(begin));
                                                            ^
/home/min/work/chiapos/src/./disk.hpp:167:60: error: expected string-literal before ‘)’ token
/home/min/work/chiapos/src/./disk.hpp: In member function ‘void FileDisk::Write(uint64_t, const uint8_t*, uint64_t)’:
/home/min/work/chiapos/src/./disk.hpp:202:60: error: expected ‘,’ before ‘)’ token
                 static_assert(sizeof(long) >= sizeof(begin));
                                                            ^
/home/min/work/chiapos/src/./disk.hpp:202:60: error: expected string-literal before ‘)’ token
In file included from /home/min/work/chiapos/src/sort_manager.hpp:30:0,
                 from /home/min/work/chiapos/src/phase1.hpp:45,
                 from /home/min/work/chiapos/src/plotter_disk.hpp:41,
                 from /home/min/work/chiapos/src/cli.cpp:20:
/home/min/work/chiapos/src/./uniformsort.hpp: At global scope:
/home/min/work/chiapos/src/./uniformsort.hpp:29:26: error: ‘UniformSort::BUF_SIZE’ declared as an ‘inline’ variable
     inline int64_t const BUF_SIZE = 262144;
                          ^
In file included from /home/min/work/chiapos/src/plotter_disk.hpp:41:0,
                 from /home/min/work/chiapos/src/cli.cpp:20:
/home/min/work/chiapos/src/phase1.hpp: In function ‘void* phase1_thread(THREADDATA*)’:
/home/min/work/chiapos/src/phase1.hpp:401:37: error: expected unqualified-id before ‘[’ token
                         const auto& [L_entry, R_entry, f_output] = current_entries_to_write[i];
                                     ^
/home/min/work/chiapos/src/phase1.hpp:401:37: error: expected initializer before ‘[’ token
/home/min/work/chiapos/src/phase1.hpp:404:77: error: ‘f_output’ was not declared in this scope
                         Bits new_entry = table_index + 1 == 7 ? std::get<0>(f_output).Slice(0, k)
                                                                             ^
/home/min/work/chiapos/src/phase1.hpp:412:48: error: ‘L_entry’ was not declared in this scope
                                 L_position_map[L_entry.pos % position_map_size] + L_position_base;
                                                ^
/home/min/work/chiapos/src/phase1.hpp:415:48: error: ‘L_entry’ was not declared in this scope
                                 R_position_map[L_entry.pos % position_map_size] + R_position_base;
                                                ^
/home/min/work/chiapos/src/phase1.hpp:417:50: error: ‘R_entry’ was not declared in this scope
                         newrpos = R_position_map[R_entry.pos % position_map_size] + R_position_base;
                                                  ^
In file included from /home/min/work/chiapos/src/phase2.hpp:22:0,
                 from /home/min/work/chiapos/src/plotter_disk.hpp:42,
                 from /home/min/work/chiapos/src/cli.cpp:20:
/home/min/work/chiapos/src/bitfield_index.hpp: At global scope:
/home/min/work/chiapos/src/bitfield_index.hpp:24:48: error: ‘kIndexBucket’ declared as an ‘inline’ field
     static inline const int64_t kIndexBucket = 1024;
                                                ^
CMakeFiles/RunTests.dir/build.make:94: recipe for target 'CMakeFiles/RunTests.dir/tests/test.cpp.o' failed
make[2]: *** [CMakeFiles/RunTests.dir/tests/test.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 39%] Building C object CMakeFiles/ProofOfSpace.dir/src/chacha8.c.o
[ 41%] Building C object CMakeFiles/ProofOfSpace.dir/src/b3/blake3.c.o
[ 44%] Linking CXX executable example
[ 44%] Built target example
Scanning dependencies of target chiapos
[ 46%] Building CXX object CMakeFiles/chiapos.dir/python-bindings/chiapos.cpp.o
[ 48%] Building C object CMakeFiles/ProofOfSpace.dir/src/b3/blake3_portable.c.o
[ 51%] Building C object CMakeFiles/ProofOfSpace.dir/src/b3/blake3_dispatch.c.o
[ 53%] Building ASM object CMakeFiles/ProofOfSpace.dir/src/b3/blake3_avx2_x86-64_unix.S.o
[ 55%] Building ASM object CMakeFiles/ProofOfSpace.dir/src/b3/blake3_avx512_x86-64_unix.S.o
[ 58%] Building ASM object CMakeFiles/ProofOfSpace.dir/src/b3/blake3_sse41_x86-64_unix.S.o
[ 60%] Building C object CMakeFiles/chiapos.dir/src/chacha8.c.o
[ 62%] Building C object CMakeFiles/chiapos.dir/src/b3/blake3.c.o
CMakeFiles/ProofOfSpace.dir/build.make:81: recipe for target 'CMakeFiles/ProofOfSpace.dir/src/cli.cpp.o' failed
make[2]: *** [CMakeFiles/ProofOfSpace.dir/src/cli.cpp.o] Error 1
CMakeFiles/Makefile2:232: recipe for target 'CMakeFiles/ProofOfSpace.dir/all' failed
make[1]: *** [CMakeFiles/ProofOfSpace.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 65%] Building C object CMakeFiles/chiapos.dir/src/b3/blake3_portable.c.o
[ 67%] Building C object CMakeFiles/chiapos.dir/src/b3/blake3_dispatch.c.o
In file included from /home/min/work/chiapos/python-bindings/../src/sort_manager.hpp:28:0,
                 from /home/min/work/chiapos/python-bindings/../src/phase1.hpp:45,
                 from /home/min/work/chiapos/python-bindings/../src/plotter_disk.hpp:41,
                 from /home/min/work/chiapos/python-bindings/chiapos.cpp:26:
/home/min/work/chiapos/python-bindings/../src/./disk.hpp: In member function ‘void FileDisk::Read(uint64_t, uint8_t*, uint64_t)’:
/home/min/work/chiapos/python-bindings/../src/./disk.hpp:167:60: error: expected ‘,’ before ‘)’ token
                 static_assert(sizeof(long) >= sizeof(begin));
                                                            ^
/home/min/work/chiapos/python-bindings/../src/./disk.hpp:167:60: error: expected string-literal before ‘)’ token
/home/min/work/chiapos/python-bindings/../src/./disk.hpp: In member function ‘void FileDisk::Write(uint64_t, const uint8_t*, uint64_t)’:
/home/min/work/chiapos/python-bindings/../src/./disk.hpp:202:60: error: expected ‘,’ before ‘)’ token
                 static_assert(sizeof(long) >= sizeof(begin));
                                                            ^
/home/min/work/chiapos/python-bindings/../src/./disk.hpp:202:60: error: expected string-literal before ‘)’ token
In file included from /home/min/work/chiapos/python-bindings/../src/sort_manager.hpp:30:0,
                 from /home/min/work/chiapos/python-bindings/../src/phase1.hpp:45,
                 from /home/min/work/chiapos/python-bindings/../src/plotter_disk.hpp:41,
                 from /home/min/work/chiapos/python-bindings/chiapos.cpp:26:
/home/min/work/chiapos/python-bindings/../src/./uniformsort.hpp: At global scope:
/home/min/work/chiapos/python-bindings/../src/./uniformsort.hpp:29:26: error: ‘UniformSort::BUF_SIZE’ declared as an ‘inline’ variable
     inline int64_t const BUF_SIZE = 262144;
                          ^
[ 69%] Building ASM object CMakeFiles/chiapos.dir/src/b3/blake3_avx2_x86-64_unix.S.o
In file included from /home/min/work/chiapos/python-bindings/../src/plotter_disk.hpp:41:0,
                 from /home/min/work/chiapos/python-bindings/chiapos.cpp:26:
/home/min/work/chiapos/python-bindings/../src/phase1.hpp: In function ‘void* phase1_thread(THREADDATA*)’:
/home/min/work/chiapos/python-bindings/../src/phase1.hpp:401:37: error: expected unqualified-id before ‘[’ token
                         const auto& [L_entry, R_entry, f_output] = current_entries_to_write[i];
                                     ^
/home/min/work/chiapos/python-bindings/../src/phase1.hpp:401:37: error: expected initializer before ‘[’ token
/home/min/work/chiapos/python-bindings/../src/phase1.hpp:404:77: error: ‘f_output’ was not declared in this scope
                         Bits new_entry = table_index + 1 == 7 ? std::get<0>(f_output).Slice(0, k)
                                                                             ^
/home/min/work/chiapos/python-bindings/../src/phase1.hpp:412:48: error: ‘L_entry’ was not declared in this scope
                                 L_position_map[L_entry.pos % position_map_size] + L_position_base;
                                                ^
/home/min/work/chiapos/python-bindings/../src/phase1.hpp:415:48: error: ‘L_entry’ was not declared in this scope
                                 R_position_map[L_entry.pos % position_map_size] + R_position_base;
                                                ^
/home/min/work/chiapos/python-bindings/../src/phase1.hpp:417:50: error: ‘R_entry’ was not declared in this scope
                         newrpos = R_position_map[R_entry.pos % position_map_size] + R_position_base;
                                                  ^
In file included from /home/min/work/chiapos/python-bindings/../src/phase2.hpp:22:0,
                 from /home/min/work/chiapos/python-bindings/../src/plotter_disk.hpp:42,
                 from /home/min/work/chiapos/python-bindings/chiapos.cpp:26:
/home/min/work/chiapos/python-bindings/../src/bitfield_index.hpp: At global scope:
/home/min/work/chiapos/python-bindings/../src/bitfield_index.hpp:24:48: error: ‘kIndexBucket’ declared as an ‘inline’ field
     static inline const int64_t kIndexBucket = 1024;
                                                ^
[ 72%] Building ASM object CMakeFiles/chiapos.dir/src/b3/blake3_avx512_x86-64_unix.S.o
[ 74%] Building ASM object CMakeFiles/chiapos.dir/src/b3/blake3_sse41_x86-64_unix.S.o
[ 76%] Linking CXX executable options_test
[ 76%] Built target options_test
CMakeFiles/chiapos.dir/build.make:81: recipe for target 'CMakeFiles/chiapos.dir/python-bindings/chiapos.cpp.o' failed
make[2]: *** [CMakeFiles/chiapos.dir/python-bindings/chiapos.cpp.o] Error 1
CMakeFiles/Makefile2:313: recipe for target 'CMakeFiles/chiapos.dir/all' failed
make[1]: *** [CMakeFiles/chiapos.dir/all] Error 2
CMakeFiles/Makefile2:205: recipe for target 'CMakeFiles/RunTests.dir/all' failed
make[1]: *** [CMakeFiles/RunTests.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by hoffmang9** [comment]
What OS and version, CPU, compiler version?

**Comment by YunL0ngLee** [comment]
OS:ubuntu-16.04.7
CPU:AMD Ryzen 5 3600 6-Core Processor
Version:tag-1.0.3

**Comment by YunL0ngLee** [comment]
> What OS and version, CPU, compiler version?

OS:ubuntu-16.04.7
CPU:AMD Ryzen 5 3600 6-Core Processor
Version:tag-1.0.3

**Comment by emlowe** [comment]
Please specify compiler version - the default GCC for Ubuntu 16 is gcc5 I believe, which is not fully c++17 compliant. I would recommend using at minimum gcc 7.

**Comment by YunL0ngLee** [comment]
> Please specify compiler version - the default GCC for Ubuntu 16 is gcc5 I believe, which is not fully c++17 compliant. I would recommend using at minimum gcc 7.

Ok,thanks a lot.I`ve already resolve it by your help.
