### ISSUE TITLE
Reduce wait time after writing failure?

### ISSUE THREAD

**Issue by ast0815** [Chia-Network/chiapos#305]
Hello all,

Today I had a disk hickup towards the end of a very long plotting process. The system remounted the disk as read-only and the plotting process reported

```
Input/output error. Retrying in five minutes.
```

over and over.

It took a bit of effort to re-mount the drive as read-writeable, but I think I was able to recover the situation by

1. Figuring out the open file handles via `lsof`
2. Force the running chia process to close the file handles with `gdb`
3. Remount the disk in read-write mode

After doing this the error messages changed to something like this:

```
Only wrote 3134 of 1048554 bytes at offset 735036354 to "/mnt/.../tmp/plot-k32...plot.p1.t4.sort_bucket_003.tmp" with length 735039488. Error 1. Retrying in five minutes.
```

And every 5 minutes a new error appears with a different bucket number in the file name.

I assume this behaviour is generated here:

https://github.com/Chia-Network/chiapos/blob/e5830b182d155f8599426a7374306445cd7c0418/src/disk.hpp#L230

My question is now twofold:

1. Will it take chia 128*5 minutes to recover the plotting process? (Or will it even just fail at the end anyway?)
2. Would it be possible/useful to reduce the delay in between tries so that the recovery happens faster? Waiting just 1 minute instead of 5 would turn a 10 h wait into a 2 h wait, which would make this actually useful if this kind of error happens towards the end of a plot. I assume the additional system load from reducing the timeout would be negligible, but maybe there is some other reason why this would be a bad idea.

Thanks in advance.

**Comment by ast0815** [comment]
So, it got to a point where it was sorting a bucket again, but then it failed differently:

```
Only wrote 3156 of 1048554 bytes at offset 736084908 to "/mnt/[...]plot.p1.t4.sort_bucket_056.tmp" with length 736088064. Error 1. Retrying in five minutes.                                                                       
        Bucket 109 QS. Ram: 1.516GiB, u_sort min: 3.250GiB, qs min: 0.813GiB. force_qs: 0                                                                                 
Only read 742372700 of 872456624 bytes at offset 0 from "/mnt/[...]plot.p1.t3.sort_bucket_109.tmp" with length 872456624. Error 0. Retrying in five minutes.
```

The latter error message is now repeating over and over.

Is this a different error from the previous ones (0 instead of 1)? It does not seem to be able to recover from it, but it also does not abort the plotting. The disk is still mounted and writeable.

**Comment by hoffmang9** [comment]
Error 0 usually indicates a hardware issue.

**Comment by ast0815** [comment]
As mentioned, there was an intermittent hardware issue. But now the disk seems to work fine. At least everything I have tried (writing files, reading files, test via `smartctl`) seems to work.

Does the error 0 mean that chia is not trying to re-generate the file? I just noticed that the number of bytes it reads changed exactly once after the first error message:

```
        Bucket 109 QS. Ram: 1.516GiB, u_sort min: 3.250GiB, qs min: 0.813GiB. force_qs: 0          
Only read 742372700 of 872456624 bytes at offset 0 from "/mnt/usb/0..2.3.2..1.0/chia/tmp/plot-k32-2021-08-09-18-54-ab37abdefa42d0f12420227c9611c2162d9e6a7984e23ee7c2319ba19a5ff678.plot.p1.t3.sort_bucket_109.tmp" with length 872456624. Error 0. Retrying in five minutes.
Only read 872456192 of 872456624 bytes at offset 0 from "/mnt/usb/0..2.3.2..1.0/chia/tmp/plot-k32-2021-08-09-18-54-ab37abdefa42d0f12420227c9611c2162d9e6a7984e23ee7c2319ba19a5ff678.plot.p1.t3.sort_bucket_109.tmp" with length 872456624. Error 0. Retrying in five minutes.
Only read 872456192 of 872456624 bytes at offset 0 from "/mnt/usb/0..2.3.2..1.0/chia/tmp/plot-k32-2021-08-09-18-54-ab37abdefa42d0f12420227c9611c2162d9e6a7984e23ee7c2319ba19a5ff678.plot.p1.t3.sort_bucket_109.tmp" with length 872456624. Error 0. Retrying in five minutes.
```

Since then it has remained constant at 872456192 and that is indeed the size of the file on disk.
