### ISSUE TITLE
Build fails on macOS Monterey 12.5.1

### ISSUE THREAD

**Issue by dariolina** [Chia-Network/chiapos#336]
cmake build from master fails on macOS Monterey 12.5.1 on both M1 and intel chip with following error:
```
...
[ 97%] Linking CXX executable ProofOfSpace
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [ProofOfSpace] Error 1
make[1]: *** [CMakeFiles/ProofOfSpace.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
2 warnings generated.
[ 97%] Built target chiapos
[100%] Linking CXX executable RunTests
[100%] Built target RunTests
make: *** [all] Error 2
```

**Comment by hoffmang9** [comment]
I just built main at commit f20f6d7bd7bdb7879167605efb2e2a21f005375e on an Intel Mac running 12.5.1 and it built successfully. I suspect I had the same two warnings but they are non fatal to the compilation.

Maybe you can add some more details?

Are you attempting to build with GCC and not the Apple tool chain - something like this - https://forum.crystal-lang.org/t/cannot-compile-statically-ld-library-not-found-for-lcrt0-o/4070 ?

`uname -a = Darwin iMac.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64`

**Comment by dariolina** [comment]
What sort of information would be helpful? I've attached the full terminal log of running the commands provided in ReadMe for statically building PoS.
I have tried this on 2 different machines ( an M1s and an Intel) with same result and have another person who confirms the same error.
`uname -a
Darwin DariiaMacBook.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64
`
[log.txt](https://github.com/Chia-Network/chiapos/files/9410444/log.txt)
.
Thank you!

**Comment by harold-b** [comment]
I think this is an issue with ld on mac because you are attempting to statically link w/ `-DBUILD_PROOF_OF_SPACE_STATICALLY`. Perhaps try changing the linker to `lld` instead of `ld`.

**Comment by harold-b** [comment]
Yes, have a look at this thread:
https://stackoverflow.com/questions/3801011/ld-library-not-found-for-lcrt0-o-on-osx-10-6-with-gcc-clang-static-flag

It might require to have its own libc built.

But, otherwise it might not be able to statically link on macOS.
More reference here: https://www.zditect.com/blog/1848115.htm
In the **Crt0.o mac** section.
