### ISSUE TITLE
Invalid size for deltas: 32770

### ISSUE THREAD

**Issue by nazar-pc** [Chia-Network/chiapos#352]
I was able to find reproduction for obscure error that was reported in some other places on the Internet in the past, but without reliable pointer to the actual issue.

Here is reproduction (note that I decreased minimal supported K to 17 because my use case requires that): https://github.com/Chia-Network/chiapos/compare/main...subspace:chiapos:reproduction-TestInvalidSizeForDeltas?w=1

This new test case will fail with:
```
.../chiapos/tests/test.cpp:1201: FAILED:
due to unexpected exception with message:
  Invalid size for deltas: 32770
```

Any ideas what is the root cause of this, maybe an actual bug or related to k17?

**Comment by hoffmang9** [comment]
We saw this pre mainnet and simply decided that tracking bugs down below k20 wasn't worth the time.
