### ISSUE TITLE
Windows 1.6 Plotter does not log an error when it runs out of memory

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/chiapos#37]
Reported by @sadams25 in https://github.com/Chia-Network/chia-blockchain/issues/263.

If your machine does not have enough memory, the windows plotter fails silently in the UI and no log is created. I had to discover the issue by running the CLU. That being said, this is a pretty minor issue as I was running this on a very underpowered VM, which is my fault.

**Comment by hoffmang9** [comment]
Closing due to being relatively antiquated - though not entirely incorrect so probably should revisit.
